### ISSUE TITLE
VertexBuffer::slice doesn't accept RangeFrom

### ISSUE THREAD

**Issue by Yamakaky** [tomaka/glium#1314]
It only accepts Range.

**Comment by Yamakaky** [comment]
https://doc.rust-lang.org/collections/range/trait.RangeArgument.html would be perfect if it wasn't unstable.

**Comment by Esption** [comment]
If/when [RangeArgument](https://doc.rust-lang.org/collections/range/trait.RangeArgument.html) becomes stable it could be used for this it looks like, but until then it's probably not going to be possible without re-implementing it or making separate functions.

@tomaka would you be fine with a temporary re-implementation of RangeArgument while waiting for it to be become stable?  If so I can get a patch for this done then.  I'm not really sure how else this could be done otherwise.

**Comment by Esption** [comment]
@Yamakaky I don't really have some code to test this on atm, could you tell me if that works? https://github.com/Esption/glium
