### ISSUE TITLE
Support for Video Texture

### ISSUE THREAD

**Issue by jagan-veeraraghavan** [tomaka/glium#1317]
As the title says, Is it possible to provide support for Video Texture. Just like how three.js supports video textures ( https://stemkoski.github.io/Three.js/Video.html). Or is there any article that talk of rendering video via glium.

**Comment by nicokoch** [comment]
I'm pretty sure this is out of the scope of this library, since it's only supposed to be a thin wrapper around opengl, not a 3d engine.

**Comment by tomaka** [comment]
Yes, you're supposed to manually decode the video yourself and upload the data to a texture before drawing.

Note that it's important that the internal format of the texture is the same as the format of the data you upload, because otherwise the OpenGL driver will perform a conversion, which takes a lot of time.
