### ISSUE TITLE
Non-clamped f32 textures? + other questions

### ISSUE THREAD

**Issue by fsh** [tomaka/glium#1379]
a) I'm really sorry if this is not the right place to "ask a question", I searched in vain for some mention of an IRC or discussion group. Please just remove it if I'm in the wrong place.

b) Q1: I have an F32F32 "texture" (GL_RG32F) where the two components actually represents (x,y) of a vector. But I can't find a way to upload it without it getting clamped to [0,1]. Some of the components might be quite large, both negative and positive. I'm fine with using F32F32F32F32 (GL_RGBA32F/GL_RGBA32F_ARB) if so be, just as long as I get unclamped values in there somehow.

I use this code:

    let raw_image = gen_vector_texture();
    // raw_image = texture::RawImage2d {
    // data: Cow::Owned(v),
    // width: maxx,
    // height: maxy,
    // format: texture::ClientFormat::F32F32F32F32
    // }
    let texture = glium::texture::Texture2d::new(&display, raw_image).unwrap();

But in the sampler every value is [0,1]?

c) Q2: I can't find a way to upload a GL_LUMINANCE texture?

d) Q3: (non-issue) I can't figure out how to use TextureAny: that is, if I create a texture with texture::any::new_texture(). Specifically, I couldn't figure out how to get a sampler out of it? (Was trying this in relation to Question 1.)

This is on Windows 10, NVIDIA Geforce 870M card.

**Comment by tomaka** [comment]
The code that creates the texture:

> let texture = glium::texture::Texture2d::new(&display, raw_image).unwrap();

Is incorrect. By default this creates a texture with an implementation-defined format, most likely U8U8U8U8.
You need to use the `with_format` constructor.

For GL_LUMINANCE, it's not supported since it's been deprecated and removed in OpenGL 3.

For the `TextureAny`, this type is not really meant to be used directly. It's more like an internal type that happens to be publicly accessible because the wrappers (like `Texture2d`) do not provide all the methods.

**Comment by fsh** [comment]
Thanks for the quick response!

I got it working, I suppose I was confusing client & internal format.
