### ISSUE TITLE
How to implement picking/selection using glium

### ISSUE THREAD

**Issue by Roxxik** [tomaka/glium#1391]
I'm currently working on a picking feature. Skimming through the glium code I found nothing hinting at direct support for it. So i want to implement my own and am not very sure how to do it,
I generally read about 3 options to picking:
- 1. Color picking: draw each object/primitive in a different color (no light/fog/particles) and just read the pixel value under your cursor
- 2. Depth only rendering: for each object/primitive: render object, read depth-buffer at mouse position, clear depth buffer. pick minimum depth object
- 3. ray casting. this one has not much to do with glium

for 1 I think i could render a scene this way, but I don't know how to render to a not on screen buffer and read a pixel value
for 2 basically the same with just depth: how to render to an only depth buffer and how to read values from it.

If someone would hint me at the functions to look at to do this I'd be happy to implement is as an example.

**Comment by tomaka** [comment]
I created a gist by copy-pasting from my project: https://gist.github.com/tomaka/d2708687a7947f02d630

The first file is a raw copy-paste, I didn't touch anything.
As you can see, at line 125 the `draw` function takes the picking texture and builds a framebuffer with it at lines 141 or 147. The shader writes to that output at line 88. The value that is written comes from the vertex attributes.

The second file shows how to use it. I have a the picking texture and a pixel buffer of size 1. At each frame, the one pixel of the buffer is read to determine what was hoving the mouse at the previous frame. Then we adjust the texture to the dimensions of the window if necessary. It then calls `ModelsSystem::draw` by passing the picking texture. Finally it copies the pixel that is under the mouse to the buffer so that it will be read at the next frame.

**Comment by tomaka** [comment]
For the record, if you want to draw to just a depth buffer, you can use `SimpleFrameBuffer::depth_only`. This function was just added by #1387 and is not yet on crates.io.

**Comment by tomaka** [comment]
And before you ask, you can't draw at the same time to the window and to the picking texture. You will have to draw the colors to a texture as well, then copy that color texture to the window with the `blit` function for example.

**Comment by Roxxik** [comment]
I'll got a [basic version](https://github.com/Roxxik/glium/blob/picking/examples/picking.rs) up and working, it's not cleand-up yet, especially the picking_target builds way too many intermediate objects and the picking assumes that id = index + 1, that is not verified anywhere. But before cleaning up I'd like to know, why the picking is not working on the edges of the model and sometimes even if the mouse is not on the model.

**Comment by Roxxik** [comment]
I just moved the camera up and something strange happened... only if aiming above the teapots I can pick them

**Comment by tomaka** [comment]
There's big problem with glium: your function call here doesn't actually clear the picking texture: https://github.com/Roxxik/glium/blob/picking/examples/picking.rs#L190

`clear` only clears floating-point textures.

It's actually the same behavior as OpenGL, but it's confusing so it should definitely be changed in glium.

You can clear the texture like this:
```
(**picking_texture).main_level().first_layer().into_image(None).unwrap().raw_clear_buffer([0u32, 0, 0, 0]);
```

**Comment by Roxxik** [comment]
Found the error, cleaned up and fixed the issue with the indices. Going to fix clearing the texture

**Comment by Roxxik** [comment]
Done

**Comment by Roxxik** [comment]
Not sure about this, but i think the SimpleFrameBuffer could be kept across calls (build outside of the loop and only rebuild after resizing) but I'm not sure whether that saves some actual resources and if it's reasonable.

**Comment by Roxxik** [comment]
#1395 made clear that this can't be done.
One implementation of basic picking can be found in #1393
