### ISSUE TITLE
Glium without Glutin

### ISSUE THREAD

**Issue by mrkishi** [tomaka/glium#553]
As far as I understand, Glium is currently tied to Glutin. Will we ever be able to use Glium without Glutin?

If so, why does Glium's context wraps, for instance, windows and event polling? How would one integrate different backends to Display/DisplayBuild? Admittedly, I'm no OpenGL expert. Can anyone shed some light on this? Was this design a requirement or will Glium leave those concerns to windowing libraries once Glutin ties are abstracted away?

Thanks!

**Comment by tomaka** [comment]
The reason why glium was tied to glutin is that glium uses a background thread which needed access to the window's functions. Therefore I needed ownership of the window and had to expose functions like `poll_events` or `wait_events`. And to avoid having a generic parameter on the `Display` for the event, I have just decided to use glutin.

I've been doing some changes recently to "un-tie" glutin from the backend. I'm not yet totally sure about what I'm going to do. There are some problems that are thought to solve, for example I need to know when the window's OpenGL context is being rebuilt so that I can clear the framebuffer objects and VAOs.

**Comment by tomaka** [comment]
Here's an idea:

```
#[derive(Clone)]
pub struct Context(...);   // opaque type, contains an Rc

pub trait ToContext {
    fn to_context(&self) -> Context;
}

impl AsContext for Display {
    ...
}
```

All glium functions (like `Texture::new`, `VertexBuffer::new`, etc.) would take a generic `&T where T: AsContext` instead of just a `&Display`. This would maintain backward-compatibility.

It would thus be possible to create multiple Display-like types: `GlutinDisplay`, `SdlDisplay`, etc.

**Comment by mrkishi** [comment]
It seems like this ToX/AsX pattern is becoming very useful in Rust!

A question: Wouldn't the `Display` type still limit the feature-availability of the multiple backends, with the additional work of creating these Display-like types? Wouldn't it make sense to base the future of Glium on `Context` instead, leaving window-related duties to the other libraries?

Take for instance the single-context multi-window use case: isn't that something the current `Display` interface can't represent? Wouldn't one have to deal with the raw `SDL` structures, bypassing `SdlDisplay`, or either re-expose those features through `SdlDisplay`? To me, it feels like Glium would be mixing different responsibilities.

**Comment by tomaka** [comment]
I'm not yet decided on this subject.

I'll leave the choice for now (between taking owernship of the backend or not) by staying retro-compatible, then I'll see what it gives.

There are some though cases, like rebuilding the context, which I'm unsure of.

**Comment by mrkishi** [comment]
What do you mean with "rebuilding the context?" I failed to find more info on it. Also, when is it needed?

**Comment by tomaka** [comment]
It's needed to switch between windowed and fullscreen for example (see the `fullscreen` example). It builds a new context by sharing lists with the old one, then destroys the old one.
The operation also needs to destroy all vertex array objects and framebuffer objects in the process, that's one of the reasons why they're stored internally.

**Comment by mrkishi** [comment]
I see!

Is that a limitation of a specific OpenGL version or platform? On Windows, for instance, I can just rebind (`MakeCurrent`) the old context to the new window, as long as they use the same pixel format.

**Comment by tomaka** [comment]
What you're doing is known to be verry buggy. It is much more reliable to just destroy the old context and recreate a new one.
