### ISSUE TITLE
Add `implement_uniforms!` macro.

### ISSUE THREAD

**Issue by TyOverby** [tomaka/glium#730]
Not sure if this is  on your todo list already, but I have manually implemented `uniforms::Uniforms` for all of my shader parameters.  Seems like this could be solved in exactly the same way that `implement_vertex!` was solved.

**Comment by tomaka** [comment]
I just realized that this is problematic because of lifetimes.

I can't write `impl Uniform for $struct { ... }`, because the struct can be `Foo<'a>` for example and that the `'a` parameter would be missing.

This is not a problem for vertices because they are static, but it is one for shader parameters.

**Comment by tomaka** [comment]
Closing as impossible.
