### ISSUE TITLE
assert_no_error() fails immediately after build_glium() in the triangle example on OSX

### ISSUE THREAD

**Issue by TyOverby** [tomaka/glium#781]
I was debugging my own program and noticed that assert_no_error() was failing after build_glium().  Inserting `assert_no_error()` into the glium triangle example also failed.

Trace file here: https://www.dropbox.com/s/lsa63yj35hso69e/triangle.trace?dl=0

**Comment by tomaka** [comment]
Does the program work?

After some investigation I think it comes from this code: https://github.com/tomaka/glium/blob/master/src/context/extensions.rs#L228

On older versions of OpenGL, you have to call `glGetString` to get the list of extensions, and on newer versions you have to call `glGetStringi`. In this code glium tries to call the former, and if it fails calls the latter. The problem is that this probably triggers a GL error.

I'll fix this to be cleaner, and add `assert_no_error` at the end of the initialization.

**Comment by TyOverby** [comment]
The program does work, but it makes it hard for me to find the _other_ error in my program :cry:

**Comment by tomaka** [comment]
I merged #782, maybe this fixes it.

**Comment by TyOverby** [comment]
This seems to have done it; thanks!

Now to find the actual error in my program! :sob:
