### ISSUE TITLE
document the undocumented public items

### ISSUE THREAD

**Issue by dcampbell24** [tomaka/glium#792]
For the sake of less warnings during compilation and documentation itself.

**Comment by tomaka** [comment]
Actually it's on purpose that I didn't remove all warnings for the moment.

The travis-ci test fails if Cargo doesn't write anything on stdout for more than 10 minutes, which is what happens if there is no warning :(
I know you can theoretically fix it with a small utility, but I didn't manage to make it work.

**Comment by dcampbell24** [comment]
Maybe [--progress](https://github.com/rust-lang/rust/issues/24335) will land in the not to distant future and then that can be used instead.

**Comment by tomaka** [comment]
Oh, that would be nice \o/
