### ISSUE TITLE
SDL2 backend

### ISSUE THREAD

**Issue by nukep** [tomaka/glium#907]
Are there any plans to implement an [SDL2](https://github.com/AngryLawyer/rust-sdl2) backend for glium in the near future? If there aren't any, then I have no problems spearheading one.

There was some interest for more backends expressed in #553, and the code base seems to support it. I have some backend questions / things that stand out for me:
* Should it be possible to feature-enable _multiple_ backends at once? i.e. both glutin and SDL2
 * It might be nice to allow dynamic backend selection at runtime (i.e. via a command line flag), but this might be out of scope.
* How would multiple backends have their documentation generated with conditional `#[cfg]` compilations? e.g. `Display` is currently an alias for `GlutinFacade`, but might be `Sdl2Facade` in an SDL2 config.

**Comment by tomaka** [comment]
I'm more interested in *removing* dependencies from glium at the moment rather than adding them.

Basically, my point of view on this subject is the following:

 - Keep glutin because it doesn't require any C library. It is always nice to have something that "just works".
 - Having a different backend is supported if the user wants to use glium on a platform that glutin doesn't support, or if glutin has a big missing feature or a nasty bug, or to use glium with Qt for example.
 - All other dependencies (`cgmath`, `nalgebra`, `image`) should ultimately be moved out if possible.

However I'm totally in favor of an `glium_sdl` crate being created if you want to do it!

**Comment by nukep** [comment]
Decoupling the dependencies is a good call. I'll look into a creating a new `glium_sdl2` crate, then. :+1:

Thanks for responding!
